# Generated by Django 4.2.3 on 2023-11-02 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0004_about_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collaboraterequest',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
